### PR TITLE
fix: support mainnet CLI network and payment guidance

### LINKED ISSUE #352: Mainnet CLI network selection and USDFC guidance regressions
Two regressions need follow-up:

- `--mainnet` / mainnet network selection is not propagated consistently through CLI auth and RPC resolution
- mainnet users without USDFC only see the minting guide instead of the bridge and swap paths that are now recommended

### PR DESCRIPTION
**Pull request by davidgasquez**
Fixes #352

- propagate `--mainnet` and network selection through CLI auth and RPC resolution
- reuse a single helper for mainnet USDFC acquisition guidance in validation and `payments status`
- make config defaults tests independent from ambient `NETWORK` and `RPC_URL`

Validation:
```sh
npm test
# Test Files  35 passed (35)
# Tests  336 passed | 11 skipped (347)
```

### CODE REVIEW

File: src/utils/cli-auth.ts [hunk 1]
```diff
@@ -26,6 +26,8 @@ export interface CLIAuthOptions {
   viewAddress?: string | undefined
   /** Filecoin network: mainnet or calibration */
   network?: string | undefined
+  /** Commander shorthand for --network mainnet */
+  mainnet?: boolean | undefined
```
Comment (rvagg) [inline src/utils/cli-auth.ts]:
```suggestion
```

**Comment by rvagg** [comment]
I pushed another commit that removes a few things, commander's `implies()` does most of the validation work for us with `--mainnet` and `--network` so we shouldn't be double-validating. Passing on the `chain` is the main fix here, the USDFC additions are very nice, and the env cleanup is good too.
