### PR TITLE
fix: add auto-fund option

### LINKED ISSUE #9: Pre-flight upload & `--auto-fund`
When doing a piece addition via `add` or `import`, you should be able to run a preflight to figure out (a) whether you're set up to do this (#6) and (b) whether you have the funds for it. `--auto-fund` (or alternatively make it automatic by default and do `--no-auto-fund` to turn it off) should make it add more funds for that operation.

e.g. in a GitHub Action, you should be able to do a `payments --setup` to make sure you're good to go and a `add --auto-fund /path/to/thing` to get it onboarded, with nothing extra.

### PR DESCRIPTION
**Pull request by SgtPooki**
add auto fund option to add/import commands

auto-fund defaults to auto-funding to 10 days (not currently overridable)

#### Reduce funds first.

```shell
npx filecoin-pin payments fund --days 8 --mode exact
┌  Filecoin Onchain Cloud Fund Adjustment
│
◇  ✓ Connected
│
│  ⚠ Warning
│    Requested runway below 10-day safety baseline.
│    WarmStorage reserves 10 days of costs; a shorter runway risks termination.
│
◇  Proceed with reducing runway below 10 days?
│  Yes
│
◇  Withdraw 0.0001 USDFC?
│  Yes
│
◇  ✓ Withdraw complete
│
│  Transaction
│    0x1adda13533584073600380b098bafa9d60f3f2c6052ebb8133e0101a6e540c28
│
│  
│  Updated
│    Deposited: 0.0009 USDFC
│    Runway: ~8 day(s)
│
└  Fund adjustment completed
```

#### add item with `auto-fund`

```shell
npx filecoin-pin add ~/Downloads/js-colo-media/IMG_1272.png --auto-fund
┌  Filecoin Pin Add
│
◇  ✓ File validated (12.8 MB)
│
◇  ✓ Connected to calibration
│
◇  ✓ Payment capacity verified
│
◇  ✓ File packed with root CID: bafybeih46vsmb4dxb6nlmtdduybphgjlc27ft57vjnrkarwbc5ac7gfkji
│
◇  ✓ IPFS content loaded (12.8 MB)
│
◇  ✓ Funding requirements met
│
│  
│  Auto-funding completed:
│    Deposited 0.0002 USDFC
│    Total deposited: 0.0010 USDFC
│    Runway: ~11 day(s) 22 hour(s)
│    Approval tx: 0xdf7f98f2f155e34eb30493a880bf286f5e3897c09c2db04b4a27788d422eb94a
│    Transaction: 0x283b3f545f9863799f6f25b323ed5f5e2f3df9fce7ac63a90934bbdcd7873852
│  
│
◇  ✓ Storage context ready
│
◇  ━━━ Add Complete ━━━
│
│  Network: calibration
│  
│  Add Details
│    File: /Users/sgtpooki/Downloads/js-colo-media/IMG_1272.png
│    Size: 12.8 MB
│    Root CID: bafybeih46vsmb4dxb6nlmtdduybphgjlc27ft57vjnrkarwbc5ac7gfkji
│  
│  Filecoin Storage
│    Piece CID: bafkzcibfzg24kait26rizarbwpuekudp5bupgms7r6gooxce4w2kaqxewmqcxib6jaqq
│    Piece ID: 41
│    Data Set ID: 240
│  
│  Storage Provider
│    Provider ID: 3
│    Name: ezpdpz-calib
│    Direct Download URL: https://calib.ezpdpz.net/piece/bafkzcibfzg24kait26rizarbwpuekudp5bupgms7r6gooxce4w2kaqxewmqcxib6jaqq
│  
│  Transaction
│    Hash: 0x8c50243c956660226aae5f85ae40a213856192658bdf9944e0e0edd5e614d183
│
└  Add completed successfully
```

Fixes #9

### CODE REVIEW

File: src/common/upload-flow.ts [hunk 1]
```diff
@@ -49,6 +51,60 @@ export interface UploadFlowResult extends SynapseUploadResult {
...
+ * Automatically ensures a minimum of 10 days of runway based on current usage + new file requirements
+ *
+ * @param synapse - Initialized Synapse instance
+ * @param fileSize - Size of file being uploaded (in bytes)
+ * @param spinner - Optional spinner for progress
+ */
+export async function performAutoFunding(
+  synapse: Synapse,
+  fileSize: number,
+  spinner?: ReturnType<typeof import('../utils/cli-helpers.js').createSpinner>
```
Comment (rvagg) [inline src/common/upload-flow.ts:65]: if we can avoid inline imports that would be preferable, I don't there's a good reason for this not to be a type import at the top of the file?

**Review by rvagg — APPROVED** [review]
