### PR TITLE
fix: pad rawSize for payment calculations

### LINKED ISSUE #213: fix: use padded rawSize for payment calculations
> [...] pad rawSize `const paddedSize = Math.ceil(size / 32) * 32` and use that for pricing in the `calculate*` functions in filecoin-pin

 _Originally posted by @SgtPooki in [#339](https://github.com/FilOzone/synapse-sdk/issues/339#issuecomment-3434938779)_

### PR DESCRIPTION
**Pull request by kaf-lamed-beyt**
`calculateRequiredAllowances()`, supposedly, is the entry point for all the calculate* functions in /core/payments.

calling `padSizeToPDPLeaves` once in it, shares that converted value with the rest.

closes #213

### CODE REVIEW

File: src/core/payments/constants.ts [hunk 1]
```diff
@@ -51,3 +51,19 @@ export const BUFFER_DENOMINATOR = 10n
...
+
+/**
+ * Pad raw size to the next multiple of 32 bytes
+ *
+ * @param rawSizeBytes - The actual size in bytes
+ * @returns Padded size (next multiple of 32)
+ */
+export function padSizeToPDPLeaves(rawSizeBytes: number): number {
+  return Math.ceil(rawSizeBytes / PDP_LEAF_SIZE) * PDP_LEAF_SIZE
+}
```
Comment (SgtPooki) [inline src/core/payments/constants.ts]: this shouldn't go in constants.ts it should probably go in a new file: `/core/payments/utils.ts`

**Review by SgtPooki — APPROVED** [review]
lgtm

**Comment by SgtPooki** [comment]
> quick one, @SgtPooki, did you eventually find the remaining `pieceSize` values?

I took a quick peek and I believe all the code does go through here.. but we may have to address this later when we run into them
